# Generated by Django 5.2.7 on 2025-12-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscan',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
