# Generated by Django 5.2.7 on 2025-12-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprep', '0002_cvscan_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscan',
            name='anonymized_cv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='hard_skill_analyser_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='identified_hard_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='identified_soft_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='preprocessed_cv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='soft_skill_analyser_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscan',
            name='summary_generator_output',
            field=models.TextField(blank=True),
        ),
    ]
