# Generated by Django 5.2.7 on 2025-12-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprep', '0003_cvscan_anonymized_cv_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscan',
            name='title',
            field=models.CharField(default='Untitled Scan', max_length=255),
        ),
    ]
