# Generated by Django 5.2.7 on 2025-12-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('UNSET', 'Unset'), ('CUSTOMER', 'Customer'), ('CVOWNER', 'CVOwner')], default='UNSET', max_length=15),
        ),
    ]
